cabal-version: 2.4
name:          hask
version:       1.0.0.0
synopsis:      A CLI note manager
license:       MIT

library
  hs-source-dirs:   src
  exposed-modules:
    Hask.Types
    Hask.Search
    Hask.Storage
    Hask.Error
    Hask.CLI
    Hask.App
    Hask.Export
    Hask.Display
  build-depends:
      base >= 4.14 && < 5
    , aeson >= 2.0
    , bytestring >= 0.10
    , directory >= 1.3
    , optparse-applicative >= 0.16
    , text >= 1.2
    , ansi-terminal >= 0.11
  default-language: Haskell2010

executable hask
  main-is:          Main.hs
  hs-source-dirs:   src
  build-depends:
      base >= 4.14 && < 5
    , hask
  default-language: Haskell2010

test-suite hask-tests
  type:             exitcode-stdio-1.0
  main-is:          Test.hs
  hs-source-dirs:   test
  build-depends:
      base >= 4.14 && < 5
    , hask
    , aeson
    , tasty
    , tasty-hunit
  default-language: Haskell2010
